name: hasura
description: Connect your Flutter/Dart apps to Hasura simply. All the power of GraphQL and Postgres in Flutter
version: 1.4.0
homepage: https://github.com/MohiuddinM/hasura_connect

dependencies:
  websocket: ^0.0.5
  http: ^0.12.2
  hive: ^1.4.1+1
  uuid: ^2.2.0
  meta: ^1.2.2


dev_dependencies:
  mockito: ^4.0.0

environment:
  sdk: '>=2.1.0 <3.0.0'
