name: hasura
description: Simple Dart library to work with Hasura GraphQL backends.
version: 1.5.0
homepage: https://github.com/MohiuddinM/hasura_connect

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  websocket: ^0.0.5
  http: ^0.12.2
  hive: ^1.0.0
  uuid: ^2.0.0
  meta: ^1.0.0


dev_dependencies:
  mockito: ^4.0.0


