name: hasura
description: Connect your Flutter/Dart apps to Hasura simply. All the power of GraphQL and Postgres in Flutter
version: 1.4.1
homepage: https://github.com/MohiuddinM/hasura_connect

dependencies:
  websocket: ^0.0.5
  http: ^0.12.2
  hive: ^1.0.0
  uuid: ^2.0.0
  meta: ^1.0.0


dev_dependencies:
  mockito: ^4.0.0

environment:
  sdk: '>=2.1.0 <3.0.0'
